# -*- coding: utf-8 -*-
from django.conf.urls import url
import apis_v1_0 as apis

urlpatterns = [
    url(r'^cart$',
        apis.cart_api),
    url(r'^order$',
        apis.order_api),
    url(r'^token$',
        apis.token),
    url(r'^pay$',
        apis.pay_unifiedorder),
    url(r'^qrcode/store/(?P<sid>[0-9]+)$',
        apis.qrcode_api),
    url(r'^qrcode/store/(?P<sid>[0-9]+)/integral/(?P<num>[0-9]+)$',
        apis.integral_qrcode_api),
    url(r'^store/(?P<sid>[0-9]+)$',
        apis.store_api),
    url(r'^code$',
        apis.code_api),
    url(r'^excel$',
        apis.upload_file_api),
    url(r'^notify$',
        apis.notify_api),
    url(r'^histories$',
        apis.order_history_api),
    url(r'^integrals$',
        apis.integral_api),
    url(r'^store/(?P<sid>[0-9]+)/integral/(?P<num>[0-9]+)$',
        apis.user_integral_api),
    url(r'^item$',
        apis.item_api),
    url(r'^store/cart$',
        apis.store_cart_api),
    url(r'^store/order$',
        apis.store_order_api),
    url(r'^store/pay-image$',
        apis.pay_image_api),
    url(r'^store/item$',
        apis.store_item_api),
    url(r'^store/bundling$',
        apis.store_bundling_api),

]
