# -*- coding: utf-8 -*-
from django.conf.urls import url
import apis_v1_1 as apis

urlpatterns = [
    url(r'^verification$',
        apis.verification_api),
    url(r'^store$',
        apis.store_api),
    url(r'^new-item$',
        apis.new_item_api),
    url(r'^item-search$',
        apis.item_search_api),
    url(r'^ring-percent$',
        apis.ring_percent_api),
    url(r'^item-status$',
        apis.item_status_api),
    url(r'^cvs-ranking$',
        apis.cvs_ranking_api),
    url(r'^notice$',
        apis.notice_api),
    url(r'^inventory$',
        apis.inventory_api),
    url(r'^user$',
        apis.user_api),
    url(r'^staff$',
        apis.staff_api),
    url(r'^staff-search$',
        apis.staff_search_api),
    url(r'^new-item-log$',
        apis.new_item_log_api),
    url(r'^new-item-search$',
        apis.new_item_search_api),
    url(r'^mobile-stock-taking$',
        apis.mobile_stock_taking_api),
    url(r'^goods-shelf-map$',
        apis.goods_shelf_map_api),
    url(r'^goods-shelf-size$',
        apis.goods_shelf_size_api),
    url(r'^item-shelf-sales$',
        apis.item_shelf_sales_api),
    url(r'^item-shelf-rebuy$',
        apis.item_shelf_rebuy_api),
    url(r'^rebuy-percent-ranking$',
        apis.rebuy_percent_ranking_api),
    url(r'^pc-stock-taking$',
        apis.pc_stock_taking_api),
]
