# -*- coding: utf-8 -*-
from django.conf.urls import url
import views

urlpatterns = [
    url(r'^manager$',
        views.get_brands,
        name='get_brands'),
    url(r'^add-brand$',
        views.add_brand,
        name='add_brand'),
    url(r'^store-commission$',
        views.store_commission,
        name='store_commission'),
    url(r'^guide-salary$',
        views.guide_salary,
        name='guide_salary'),
    url(r'^upload$',
        views.upload,
        name='upload'),
    url(r'^goods-manage$',
        views.goods_manage,
        name='goods_manage'),
    url(r'^guide-manage$',
        views.guide_manage,
        name='guide_manage'),
    url(r'^upload-rebate$',
        views.upload_rebate,
        name='upload_rebate'),
    url(r'^guide-checkin-map$',
        views.guide_checkin_map,
        name='guide_checkin_map'),
    url(r'^sales$',
        views.sales,
        name='sales'),
    url(r'^sales-detail$',
        views.sales_detail,
        name='sales'),
    url(r'^guide$',
        views.guide,
        name='guide'),
    url(r'^goods$',
        views.goods,
        name='goods'),
    url(r'^checkin$',
        views.checkin,
        name='checkin'),
    url(r'^realtime-checkin$',
        views.realtime_checkin,
        name='realtime-checkin'),
    url(r'^activity$',
        views.activity,
        name='activity'),
    url(r'^store$',
        views.store,
        name='store'),
]
