# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 05:01
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u5458',
                'verbose_name_plural': '\u7ba1\u7406\u5458',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=200, verbose_name='\u4f01\u4e1a\u6807\u51c6\u540d\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('telephone', models.CharField(max_length=200, null=True, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name': '\u54c1\u724c',
                'verbose_name_plural': '\u54c1\u724c',
            },
        ),
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='\u8fde\u9501\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='ChangePlanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_type', models.IntegerField(choices=[(0, '\u65e9\u73ed'), (1, '\u4e2d\u73ed'), (2, '\u665a\u73ed'), (3, '\u5927\u73ed'), (4, '\u4f11\u606f'), (5, '\u591c\u73ed')], null=True, verbose_name='\u4fee\u6539\u540e\u7c7b\u578b')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_address', models.CharField(max_length=255, null=True, verbose_name='\u4e0a\u73ed\u7b7e\u5230\u5730\u5740')),
                ('work_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='\u4e0a\u73ed\u7b7e\u5230\u7ecf\u5ea6')),
                ('work_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='\u4e0a\u73ed\u7b7e\u5230\u7eac\u5ea6')),
                ('work_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u4e0a\u73ed\u7b7e\u5230\u65f6\u95f4')),
                ('worked_address', models.CharField(max_length=255, null=True, verbose_name='\u4e0b\u73ed\u7b7e\u5230\u5730\u5740')),
                ('worked_lng', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='\u4e0b\u73ed\u7b7e\u5230\u7ecf\u5ea6')),
                ('worked_lat', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='\u4e0b\u73ed\u7b7e\u5230\u7eac\u5ea6')),
                ('worked_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='\u4e0b\u73ed\u7b7e\u5230\u65f6\u95f4')),
                ('phone_model', models.CharField(max_length=128, null=True, verbose_name='\u624b\u673a\u578b\u53f7')),
                ('phone_platform', models.CharField(max_length=128, null=True, verbose_name='\u5ba2\u6237\u7aef\u5e73\u53f0')),
                ('phone_system', models.CharField(max_length=128, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c')),
            ],
        ),
        migrations.CreateModel(
            name='CheckinExceptionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_type', models.IntegerField(choices=[(1, '\u8fdf\u5230'), (2, '\u65e9\u9000')], verbose_name='\u5f02\u5e38\u7c7b\u578b')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('checkin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Checkin', verbose_name='\u7b7e\u5230\u8bb0\u5f55')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitiveMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=256, verbose_name='\u5c0f\u7a0b\u5e8fappid')),
                ('secret', models.CharField(max_length=256, verbose_name='\u5c0f\u7a0b\u5e8fsecret')),
                ('mch_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5546\u6237\u53f7ID')),
                ('pay_api_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u652f\u4ed8\u7b7e\u540d\u79d8\u94a5')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Brand', verbose_name='\u54c1\u724c\u5546')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=200, verbose_name='\u5546\u54c1\u6761\u7801')),
                ('name', models.CharField(max_length=200, verbose_name='\u5546\u54c1\u540d\u79f0')),
                ('inside_code', models.CharField(max_length=200, null=True, verbose_name='\u5546\u54c1\u5185\u7801')),
                ('unite', models.CharField(max_length=200, null=True, verbose_name='\u5546\u54c1\u89c4\u683c')),
                ('factory_price', models.FloatField(default=0, null=True, verbose_name='\u51fa\u5382\u4ef7')),
                ('delivery_price', models.FloatField(default=0, null=True, verbose_name='\u4f9b\u8d27\u4ef7')),
                ('price', models.FloatField(default=0, null=True, verbose_name='\u96f6\u552e\u4ef7')),
                ('commission', models.FloatField(default=0, null=True, verbose_name='\u63d0\u6210')),
                ('is_mainline', models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u4e3b\u7ebf\u4ea7\u54c1')),
                ('category_id', models.IntegerField(null=True, verbose_name='\u65b0\u6807\u51c6\u5206\u7c7bID')),
                ('is_competitive', models.BooleanField(db_index=True, default=False, verbose_name='\u662f\u5426\u662f\u7ade\u54c1')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u7cfb\u5217\u540d\u79f0')),
                ('group_code', models.CharField(max_length=200, null=True, verbose_name='\u7cfb\u5217\u7f16\u7801')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Brand', verbose_name='\u54c1\u724c')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u7528\u6237\u540d\u79f0')),
                ('telephone', models.CharField(db_index=True, max_length=200, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('staff_number', models.CharField(max_length=255, null=True, verbose_name='\u5458\u5de5\u7f16\u53f7')),
                ('status', models.IntegerField(choices=[(0, '\u5728\u804c'), (1, '\u4f11\u5047'), (2, '\u79bb\u804c'), (3, '\u77ed\u4fc3')], null=True, verbose_name='\u5728\u5c97\u72b6\u6001')),
                ('openid', models.CharField(db_index=True, max_length=256, null=True, verbose_name='\u7528\u6237\u5728\u5fae\u4fe1\u7684\u552f\u4e00id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('basic_salary', models.FloatField(default=0, null=True, verbose_name='\u5e95\u85aa')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Brand', verbose_name='\u54c1\u724c')),
            ],
            options={
                'verbose_name': '\u5bfc\u8d2d\u5458',
                'verbose_name_plural': '\u5bfc\u8d2d\u5458',
            },
        ),
        migrations.CreateModel(
            name='GuideLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='\u540d\u5b57')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('openid', models.CharField(db_index=True, max_length=256, null=True, verbose_name='\u7528\u6237\u5728\u5fae\u4fe1\u7684\u552f\u4e00id')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Brand', verbose_name='\u54c1\u724c\u5546')),
            ],
        ),
        migrations.CreateModel(
            name='GuideLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_begin', models.DateField(blank=True, null=True, verbose_name='\u8bf7\u5047\u5f00\u59cb\u65e5\u671f')),
                ('leave_end', models.DateField(blank=True, null=True, verbose_name='\u8bf7\u5047\u7ed3\u675f\u65e5\u671f')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u8bf7\u5047\u5907\u6ce8\u4fe1\u606f')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Guide', verbose_name='\u5bfc\u8d2d\u5458')),
            ],
        ),
        migrations.CreateModel(
            name='GuideWorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.IntegerField(choices=[(0, '\u65e9\u73ed'), (1, '\u4e2d\u73ed'), (2, '\u665a\u73ed'), (3, '\u5927\u73ed'), (4, '\u4f11\u606f'), (5, '\u591c\u73ed')], null=True, verbose_name='\u5de5\u4f5c\u7c7b\u578b')),
                ('date', models.DateField(null=True, verbose_name='\u8ba1\u5212\u65e5\u671f')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Guide', verbose_name='\u5bfc\u8d2d\u5458')),
                ('guide_leave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.GuideLeave', verbose_name='\u8bf7\u5047\u8bb0\u5f55')),
            ],
        ),
        migrations.CreateModel(
            name='ItemRebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebate', models.FloatField(null=True, verbose_name='\u8fd4\u5229\u91d1\u989d')),
                ('compute_unit', models.CharField(max_length=168, null=True, verbose_name='\u8fd4\u5229\u8ba1\u91cf\u5355\u4f4d')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Goods', verbose_name='\u5546\u54c1')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100, null=True, verbose_name='\u8bf7\u5047\u7c7b')),
                ('should_payoff', models.FloatField(null=True, verbose_name='\u5e94\u53d1\u5de5\u8d44\u767e\u5206\u6bd4')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeChackinRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(verbose_name='\u5355\u9879\u7b7e\u5230\u65f6\u95f4'), blank=True, null=True, size=None, verbose_name='\u5373\u65f6\u8003\u52e4\u65f6\u95f4')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Brand', verbose_name='\u54c1\u724c\u5546')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='\u5b9e\u65f6\u7b7e\u5230\u5730\u5740')),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='\u5b9e\u65f6\u7b7e\u5230\u7ecf\u5ea6')),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='\u5b9e\u65f6\u7b7e\u5230\u7eac\u5ea6')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='\u5b9e\u65f6\u7b7e\u5230\u65f6\u95f4')),
                ('phone_model', models.CharField(max_length=128, null=True, verbose_name='\u624b\u673a\u578b\u53f7')),
                ('phone_platform', models.CharField(max_length=128, null=True, verbose_name='\u5ba2\u6237\u7aef\u5e73\u53f0')),
                ('phone_system', models.CharField(max_length=128, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Guide', verbose_name='\u5bfc\u8d2d\u5458')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeCheckinExceptionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('exception_type', models.IntegerField(blank=True, choices=[(1, '\u8fdf\u5230'), (2, '\u65e9\u9000')], null=True, verbose_name='\u5f02\u5e38\u7c7b\u578b')),
                ('checkin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.RealTimeCheck', verbose_name='\u7b7e\u5230\u8bb0\u5f55')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Guide', verbose_name='\u5bfc\u8d2d')),
            ],
        ),
        migrations.CreateModel(
            name='RebateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(null=True, verbose_name='\u6570\u91cf')),
                ('store_receipts_url', models.CharField(blank=True, max_length=1024, null=True, verbose_name='\u5c0f\u7968URL')),
                ('red_packets', models.CharField(max_length=1024, null=True, verbose_name='\u7ea2\u5305\u4e8c\u7ef4\u7801URL')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('store_receipts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256, null=True), null=True, size=None, verbose_name='\u591a\u5f20\u5c0f\u7968URL')),
                ('qrcode', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u4e8c\u7ef4\u7801')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Guide', verbose_name='\u5bfc\u8d2d\u5458')),
                ('item_rebate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.ItemRebate', verbose_name='\u5546\u54c1\u8fd4\u5229')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(null=True, verbose_name='\u671f\u521d\u5e93\u5b58')),
                ('middle', models.IntegerField(null=True, verbose_name='\u671f\u95f4\u8fdb\u8d27')),
                ('sales', models.IntegerField(null=True, verbose_name='\u9500\u91cf\u6570\u636e')),
                ('end', models.IntegerField(null=True, verbose_name='\u671f\u672b\u5e93\u5b58')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Goods', verbose_name='\u5546\u54c1')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Guide', verbose_name='\u64cd\u4f5c\u5458')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, null=True, verbose_name='\u95e8\u5e97\u540d\u79f0')),
                ('store_address', models.CharField(max_length=255, null=True, verbose_name='\u95e8\u5e97\u5730\u5740')),
                ('lng', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='\u95e8\u5e97\u7ecf\u5ea6')),
                ('lat', models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True, verbose_name='\u95e8\u5e97\u7eac\u5ea6')),
                ('shopkeeper_name', models.CharField(max_length=255, null=True, verbose_name='\u5e97\u4e3b\u59d3\u540d')),
                ('shopkeeper_phone_number', models.CharField(max_length=200, null=True, verbose_name='\u5e97\u4e3b\u8054\u7cfb\u65b9\u5f0f')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('number', models.CharField(max_length=255, null=True, verbose_name='\u95e8\u5e97\u7f16\u53f7')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Brand', verbose_name='\u54c1\u724c')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Chain', verbose_name='\u8fde\u9501\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='\u4e0a\u73ed\u8d77\u59cb\u65f6\u95f4')),
                ('spread', models.IntegerField(blank=True, null=True, verbose_name='\u4e0a\u73ed\u8de8\u5ea6(\u5206\u949f)')),
                ('work_type', models.IntegerField(choices=[(0, '\u65e9\u73ed'), (1, '\u4e2d\u73ed'), (2, '\u665a\u73ed'), (3, '\u5927\u73ed'), (4, '\u4f11\u606f'), (5, '\u591c\u73ed')], verbose_name='\u6392\u73ed\u7c7b\u578b')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Store', verbose_name='\u95e8\u5e97')),
            ],
        ),
        migrations.AddField(
            model_name='statement',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Store', verbose_name='\u95e8\u5e97'),
        ),
        migrations.AddField(
            model_name='guideleave',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.LeaveType', verbose_name='\u8bf7\u5047\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='guide',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.GuideLeader', verbose_name='\u76f4\u5c5e\u9886\u5bfc'),
        ),
        migrations.AddField(
            model_name='guide',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Store', verbose_name='\u95e8\u5e97'),
        ),
        migrations.AddField(
            model_name='goods',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Groups', verbose_name='\u5546\u54c1\u5206\u7ec4'),
        ),
        migrations.AddField(
            model_name='competitivemap',
            name='brand_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_goods', to='dailystatement.Goods', verbose_name='\u54c1\u724c\u5546\u54c1'),
        ),
        migrations.AddField(
            model_name='competitivemap',
            name='competitive_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitive_goods', to='dailystatement.Goods', verbose_name='\u7ade\u54c1'),
        ),
        migrations.AddField(
            model_name='checkinexceptionlog',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Guide', verbose_name='\u5bfc\u8d2d'),
        ),
        migrations.AddField(
            model_name='checkinexceptionlog',
            name='guide_work_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.GuideWorkPlan', verbose_name='\u5bfc\u8d2d\u6392\u73ed'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Guide', verbose_name='\u5bfc\u8d2d\u5458'),
        ),
        migrations.AddField(
            model_name='changeplanlog',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailystatement.GuideWorkPlan', verbose_name='\u8ba1\u5212'),
        ),
        migrations.AddField(
            model_name='additemlog',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Goods', verbose_name='\u5546\u54c1'),
        ),
        migrations.AddField(
            model_name='additemlog',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailystatement.Guide', verbose_name='\u5bfc\u8d2d\u5458'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set([('store_name', 'brand')]),
        ),
        migrations.AlterUniqueTogether(
            name='guide',
            unique_together=set([('name', 'brand', 'store')]),
        ),
        migrations.AlterUniqueTogether(
            name='goods',
            unique_together=set([('name', 'groups')]),
        ),
    ]
