# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailystatement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='worked_time',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='\u4e0b\u73ed\u7b7e\u5230\u65f6\u95f4'),
        ),
    ]
