# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopplus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyOffCoupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='\u4f18\u60e0\u91d1\u989d')),
                ('off_money', models.FloatField(verbose_name='\u8fbe\u6807\u91d1\u989d')),
                ('start_date', models.DateField(auto_now_add=True, null=True, verbose_name='\u5f00\u59cb\u65e5\u671f')),
                ('finish_date', models.DateField(auto_now_add=True, null=True, verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('inroduce', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7ea6\u675f\u8bf4\u660e')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopplus.Store', verbose_name='\u95e8\u5e97')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOffCouponsUserMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u4f7f\u7528')),
                ('money_off_counpons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopplus.MoneyOffCoupons', verbose_name='\u6ee1\u51cf\u4f18\u60e0\u5238')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopplus.User', verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u672c\u6b21\u8ba2\u5355\u7684\u6536\u8d27\u5730\u5740'),
        ),
    ]
