# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 01:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopplus', '0002_auto_20180306_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5546\u54c1\u9996\u56fe'),
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5355\u4e2a\u56fe\u7247'), blank=True, null=True, size=None, verbose_name='\u5546\u54c1\u7684\u5168\u90e8\u56fe\u7247'),
        ),
    ]
