# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopplus', '0004_order_money_off_counpons'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVSConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=256, verbose_name='\u5c0f\u7a0b\u5e8fappid')),
                ('secret', models.CharField(max_length=256, verbose_name='\u5c0f\u7a0b\u5e8fsecret')),
                ('mch_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u5546\u6237\u53f7ID')),
                ('pay_api_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='\u652f\u4ed8\u7b7e\u540d\u79d8\u94a5')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopplus.Store', verbose_name='\u95e8\u5e97')),
            ],
        ),
    ]
