# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopplus', '0006_user_app_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5546\u54c1\u4e0a\u67b6\u6570\u91cf'),
        ),
    ]
