# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopplus', '0008_item_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='uint',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='\u9500\u552e\u5355\u4f4d'),
        ),
    ]
