# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopplus', '0009_item_uint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='write_off_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='\u6838\u9500\u7801'),
        ),
        migrations.AddField(
            model_name='order',
            name='write_off_status',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u6838\u9500'),
        ),
    ]
